version: "3.9"
services:
  backend:
    build: .
    container_name: songs-app-backend
    ports:
      - "3000:3000"
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=songsdb
      - PGPORT=5432
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    container_name: songs-app-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

  db:
    image: postgres:15
    container_name: songs-app-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: songsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
# # version: "3.9"
# services:
#   backend:
#     build: .
#     container_name: songs-app-backend
#     ports:
#       - "3000:3000"
#     environment:
#       - PGHOST=db
#       - PGUSER=postgres
#       - PGPASSWORD=postgres
#       - PGDATABASE=songsdb
#       - PGPORT=5432
#     depends_on:
#       - db
#     volumes:
#       - ./backend:/app/backend
#       - /app/backend/node_modules

#   frontend:
#     image: nginx:alpine
#     container_name: songs-app-frontend
#     volumes:
#       - ./frontend:/usr/share/nginx/html:ro
#     ports:
#       - "8080:80"

#   db:
#     image: postgres:15
#     container_name: songs-app-db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: songsdb
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
